# Generated by Django 5.1 on 2024-08-21 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_site', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='habits',
            name='strike_count',
            field=models.IntegerField(default=0),
        ),
    ]
