# Generated by Django 5.1 on 2024-08-21 22:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_site', '0002_habits_strike_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='habits',
            name='is_checked_today',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='habits',
            name='last_checked',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
